"""add pdf fields to proposta

Revision ID: add_pdf_fields_to_proposta
Revises: d40f383ff0d1
Create Date: 2025-01-08 15:00:00.000000

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'add_pdf_fields_to_proposta'
down_revision = 'd40f383ff0d1'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('proposta', sa.Column('pdf_gerado', sa.Boolean(), nullable=True, default=False))
    op.add_column('proposta', sa.Column('pdf_caminho', sa.String(length=500), nullable=True))
    op.add_column('proposta', sa.Column('pdf_data_geracao', sa.DateTime(), nullable=True))
    op.create_index(op.f('ix_proposta_pdf_gerado'), 'proposta', ['pdf_gerado'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_proposta_pdf_gerado'), table_name='proposta')
    op.drop_column('proposta', 'pdf_data_geracao')
    op.drop_column('proposta', 'pdf_caminho')
    op.drop_column('proposta', 'pdf_gerado')
    # ### end Alembic commands ###
