"""add abertura_empresa to clientes

Revision ID: d40f383ff0d1
Revises: 
Create Date: 2025-08-11 13:25:45.148707
"""

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd40f383ff0d1'
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('clientes', schema=None) as batch_op:
        batch_op.add_column(sa.Column('abertura_empresa', sa.Boolean(), server_default=sa.text('0'), nullable=False))

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('clientes', schema=None) as batch_op:
        batch_op.drop_column('abertura_empresa')

    # ### end Alembic commands ###
